// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKnN4MrjtcER0jHaIAHOQwnJDsC32wM1s',
    appId: '1:36954955132:web:58a0241ea48f03e2bb98f9',
    messagingSenderId: '36954955132',
    projectId: 'mindmate-ai-10604',
    authDomain: 'mindmate-ai-10604.firebaseapp.com',
    storageBucket: 'mindmate-ai-10604.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8SGeIFmPy-xs4icQiV2qhkQ3KrNP_0So',
    appId: '1:36954955132:android:1f3808753830ba53bb98f9',
    messagingSenderId: '36954955132',
    projectId: 'mindmate-ai-10604',
    storageBucket: 'mindmate-ai-10604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUZC8T1IcxrDSZf0T9DLsPpOsngqYcuAk',
    appId: '1:36954955132:ios:d2297aa4f29e4e9fbb98f9',
    messagingSenderId: '36954955132',
    projectId: 'mindmate-ai-10604',
    storageBucket: 'mindmate-ai-10604.firebasestorage.app',
    iosBundleId: 'com.example.mindmateAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUZC8T1IcxrDSZf0T9DLsPpOsngqYcuAk',
    appId: '1:36954955132:ios:d2297aa4f29e4e9fbb98f9',
    messagingSenderId: '36954955132',
    projectId: 'mindmate-ai-10604',
    storageBucket: 'mindmate-ai-10604.firebasestorage.app',
    iosBundleId: 'com.example.mindmateAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKnN4MrjtcER0jHaIAHOQwnJDsC32wM1s',
    appId: '1:36954955132:web:73abc3896985cbc8bb98f9',
    messagingSenderId: '36954955132',
    projectId: 'mindmate-ai-10604',
    authDomain: 'mindmate-ai-10604.firebaseapp.com',
    storageBucket: 'mindmate-ai-10604.firebasestorage.app',
  );
}
